adding fonts
YuliaSimanavets/RingSizer pull request #6
Opened 2023-12-05 13:30 UTC by YuliaSimanavets

2023-12-05 13:42 UTC, vkostechko-applace requested changes

2023-12-05 13:42 UTC, vkostechko-applace commented on RingSizer/Base/Extensions/Fonts.swift
> +    static func roundedRegular(size: CGFloat) -> UIFont {
please update swift gen config and use here generated enum

2023-12-05 14:54 UTC, YuliaSimanavets commented on RingSizer/Base/Extensions/Fonts.swift
> +    static func roundedRegular(size: CGFloat) -> UIFont {
got it

2023-12-06 10:04 UTC, YuliaSimanavets commented on RingSizer/Base/Extensions/Fonts.swift
> +    static func roundedMedium(size: CGFloat) -> UIFont {
thanks, fixed it

2023-12-06 10:15 UTC, vkostechko-applace requested changes

2023-12-06 10:15 UTC, vkostechko-applace commented on RingSizer/Base/Extensions/UIFonts.swift
> +    }
it could be better. Attaching example 
<img width="597" alt="PDFScanner_—_UIFont_Utils_swift_—_Edited" src="https://github.com/YuliaSimanavets/RingSizer/assets/152169284/bec32759-dca3-4468-b555-665f114f36bf">

2023-12-06 10:22 UTC, YuliaSimanavets commented on RingSizer/Base/Extensions/UIFonts.swift
> +    }
how succinct :) corrected

2023-12-06 11:42 UTC, vkostechko-applace approved these changes

2023-12-06 11:42 UTC, merged